title: <p align="center"> Naga Manasa Surikuchi </p>
logo: /assets/img/IMG_20210212_171912.jpg

description:
  <p align="center">
  <a href="www.linkedin.com/in/naga-manasa-surikuchi-0309b353">LinkedIn</a> |
  <a href="https://github.com/SNManasa">GitHub</a>
  
  <br>   
  I'm working on SAP Architechtures, Build, Uprade, Migrations and Implementations.
  I am learning Machine Learning and Artificial Intellignece.
  Worked with Cognizant Technologies pvt ltd. and Yash Technologies pvt ltd.
  Working in SAP Technology for 9plus years.
  <br>
  </p>



theme: jekyll-theme-minimal
