title: <p align="center"> Naga Manasa Surikuchi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="www.linkedin.com/in/naga-manasa-surikuchi-0309b353">LinkedIn</a> |
  <a href="https://github.com/SNManasa">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
